version: '3'
volumes:
    postgresDB:
networks:
        web:
services:
  postgres:
    image: postgres

    networks:
            - web
    ports:
      - 5432:5432
    expose:
            - 5432
    env_file:
      - .env.secret

    volumes:
      - postgresDB:/var/lib/postgresqel/data
  django:
    tty: true
    build: ./src/django_backend/
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/django_backend/:/django
    networks:
            - web
    ports:
      - "8000:8000"
    depends_on:
      - postgres
