version: '3'

services:
  postgres:
    image: postgres
  django:
    build: ./src/django_backend/
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/django_backend:/django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
